services:
  backend:
    build:
      context: ./expressjs-and-rest-MeghanaSpurthiM
      dockerfile: Dockerfile # Ensure the Dockerfile exists in this directory
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    dns:
      - 8.8.8.8

  frontend:
    build:
      context: ./React/task-manager
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3000
    dns:
      - 8.8.8.8